title: Out of Bounds
description: KOK

url: http://KimSungYoon-KOK.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Project
    url: /project.html
  - title: Algorithm
    url: /algorithm.html
  - title: About
    url: /about
  

social:
  github: https://github.com/KimSungYoon-KOK
  twitter: 
  facebook: 
  email: sungyun1997@gmail.com

google_analytics: "UA-58263416-1"
